services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mft-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Mft!DevPassw0rd"
      MSSQL_PID: "Developer"
    ports:
      - "14330:1433"
    volumes:
      - mft-sqlserver-data:/var/opt/mssql

volumes:
  mft-sqlserver-data:
